### ISSUE TITLE
How can I use the PractRand with your code?

### ISSUE THREAD

**Issue by menwn** [KilianB/pcg-java#3]
Could you please give an example on how to use the PractRand with your library to test the outcome?

**Comment by KilianB** [comment]
The file https://github.com/KilianB/pcg-java/blob/master/src/main/java/com/github/kilianB/statBenchmark/PractRandInterface.java was used to call the practRand.exe

**Comment by menwn** [comment]
Thank you. I was able to use this file to understand what you do. Great job. However one thing is that if I use nextInt(10) (or any integer as upper limit that I tested) I get failure from the PractRand. I am not sure why this is the case. I would expect that it would pass. Or is this a case where the space is too little to be used by PractRand?

**Comment by KilianB** [comment]
Without taking a look at pract rand one of the tests probably checks the individual bit distribution of the supplied numbers and expects a known distribution.

If you only supply values up to 9 , you will pass values starting from 
0000000000000000 to 0000000000001001 to the algorithm (a few leading zeros more or less). Since the high bits are always 0 it assumes that the random numbers are not randomly distributed.

**Comment by menwn** [comment]
Thank you
